//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSKUID
    {
        public tblSKUID()
        {
            this.tblBasePromotions = new HashSet<tblBasePromotion>();
            this.tblCarts = new HashSet<tblCart>();
        }
    
        public int SKUId { get; set; }
        public string Name { get; set; }
        public int UnitPrice { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<tblBasePromotion> tblBasePromotions { get; set; }
        public virtual ICollection<tblCart> tblCarts { get; set; }
    }
}
